wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: huggingface
    huggingface_version: 4.6.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.7
    t:
      1:
      - 1
      - 11
      4: 3.7.7
      5: 0.10.30
      6: 4.6.1
      8:
      - 1
      - 2
      - 5
